# Generated by Django 4.0.6 on 2022-07-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='Serial Number')),
                ('card_number', models.BigIntegerField(verbose_name='Card Number')),
                ('release_date', models.DateTimeField(verbose_name='Release Date')),
                ('exp_date', models.DateTimeField(verbose_name='Expire Date')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('balance', models.FloatField(verbose_name='Balance')),
                ('card_status', models.CharField(default='activated', max_length=25, verbose_name='Card Status')),
            ],
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
            ],
        ),
    ]
