# Generated by Django 4.0.6 on 2022-07-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='Serial Number')),
                ('card_number', models.BigIntegerField(verbose_name='Card Number')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='Release Date')),
                ('end_date', models.DateTimeField(verbose_name='Expire Date')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('money_on_card', models.FloatField(verbose_name='Amount of Money')),
                ('card_status', models.CharField(default='activated', max_length=25, verbose_name='Card Status')),
            ],
        ),
    ]
